server:
  port: 41002
  servlet:
    context-path: /base
spring:
  application:
    name: whh-base
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://29.28.147.157:16063/ghi?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    maxActive: 20
    initialSize: 20
    maxWait: 2000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    username: ghi
    password: ENC(Ye09VIyrH2SPeonTwEsxt17jKjM8VvfE/5rxO2a55vo=)
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    fetch-registry: true
    service-url:
      #defaultZone: http://127.0.0.1:8151/eureka
      defaultZone: http://admin:admin123456@127.0.0.1:30000/eureka
      #defaultZone: http://admin:admin123456@29.23.3.44/eureka
logging:
  config: classpath:logback-spring.xml

ribbon:
  ConnectTimeout: 50000 #????????? ?????? 1 ?
  ReadTimeout: 50000  #?????????
  MaxAutoRetriesNextServer: 0 #???????
LtcExcelFeign:
  ribbon:
    ConnectTimeout: 30000
    ReadTimeout: 30000
    MaxAutoRetriesNextServer: 0
#feignClient??
feign:
  httpclient:
    enabled: true
    connection-timeout: 50000
  hystrix:
    enabled: true #??feign??
hystrix.command.LtcExcelFeign#validAndSave.execution.isolation.thread.timeoutInMilliseconds: 300000
#????
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000
