server:
  port: 20000
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin123456@127.0.0.1:20000/eureka
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 100
spring:
  security:
    user:
      name: admin
      password: admin123456